services:
  frontend:
    from:
      - node:23-alpine

    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - PB_API_URL=http://backend:8090
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: development
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - /app/go/pkg
    environment:
      - GO_ENV=development
      - PB_DATA_DIR=/app/pb_data
    command: go run main.go serve
